services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    ports:
      - "8088:8080"
