"""carwash tables

Revision ID: 2fabef2007b6
Revises: 8102ee17cd99
Create Date: 2024-12-23 15:45:24.932959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fabef2007b6"
down_revision: Union[str, None] = "8102ee17cd99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_table(
        "cars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_cars_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cars")),
    )
    op.create_table(
        "customer_cars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("number", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["car_id"], ["cars.id"], name=op.f("fk_customer_cars_car_id_cars")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["user.id"],
            name=op.f("fk_customer_cars_customer_id_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_cars")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("administrator_id", sa.Integer(), nullable=True),
        sa.Column("customer_car_id", sa.Integer(), nullable=True),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["administrator_id"],
            ["user.id"],
            name=op.f("fk_orders_administrator_id_user"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_car_id"],
            ["customer_cars.id"],
            name=op.f("fk_orders_customer_car_id_customer_cars"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["user.id"],
            name=op.f("fk_orders_employee_id_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_table(
        "order_service",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_service_order_id_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_order_service_service_id_services"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_service")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("order_service")
    op.drop_table("orders")
    op.drop_table("customer_cars")
    op.drop_table("cars")
    op.drop_table("services")
    op.drop_table("brands")
    # ### end Alembic commands ###
