"""Set default for is_send_notify

Revision ID: b313d5553b6e
Revises: 8d1ece8c6d5a
Create Date: 2024-12-22 23:20:35.755912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b313d5553b6e"
down_revision: Union[str, None] = "8d1ece8c6d5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "user", sa.Column("first_name", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "user", sa.Column("last_name", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "user", sa.Column("patronymic", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "user", sa.Column("is_send_notify", sa.Boolean(), nullable=False)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("user", "is_send_notify")
    op.drop_column("user", "patronymic")
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")


    # ### end Alembic commands ###
