"""add username

Revision ID: b203ed384827
Revises: 2fabef2007b6
Create Date: 2024-12-26 20:31:20.173609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b203ed384827"
down_revision: Union[str, None] = "2fabef2007b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "user", sa.Column("username", sa.String(length=50), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("user", "username")


    # ### end Alembic commands ###
