"""Add notified field to User

Revision ID: 33993442c3bc
Revises: 35b129e0e839
Create Date: 2025-01-04 17:16:00.998931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33993442c3bc"
down_revision: Union[str, None] = "35b129e0e839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "orders", sa.Column("notified", sa.Boolean(), nullable=False, server_default=sa.false())
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("orders", "notified")

    # ### end Alembic commands ###
