"""Add notified field to User

Revision ID: 35b129e0e839
Revises: 2e1ab68e9c95
Create Date: 2025-01-04 17:14:37.769623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35b129e0e839"
down_revision: Union[str, None] = "2e1ab68e9c95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "company",
        "id",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
        autoincrement=True,
    )
    op.add_column(
        "orders", sa.Column("notified", sa.Boolean(), nullable=False)
    )
    op.alter_column(
        "tasks",
        "id",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "user",
        "id",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("user", "notified")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "notified",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "user",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "tasks",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("orders", "notified")
    op.alter_column(
        "company",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
